### ISSUE TITLE
How do I fix this? 

### ISSUE THREAD

**Issue by Brumbpo-Tungus** [DedSecInside/TorBot#180]
Traceback (most recent call last):
  File "torBot.py", line 10, in <module>
    from modules.analyzer import LinkTree
ImportError: No module named analyzer
[4542] Failed to execute script torBot

What have I done wrong in the process of installing?

**Comment by SubaruSama** [comment]
That's odd. In the code of torBot.py, in line 10, it is referencing the right module, and in the module is all good. Have you tried again?
My suggestion is: create a python virtual env, clone the repo and install the dependencies.

**Comment by JeffBarron** [comment]
I have the same issue.

**Comment by KingAkeem** [comment]
How are you executing `torBot.py` and what version of Python are you using?

**Comment by samitbrc** [comment]
oh I have created another issue like this
my python is 3.8.2
os is kali

**Comment by samitbrc** [comment]
File "torBot.py", line 10, in <module>
    from modules.analyzer import LinkTree
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "modules/analyzer.py", line 6, in <module>
    from ete3 import Tree, TreeStyle, TextFace, add_face_to_node
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/ete3/__init__.py", line 51, in <module>
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/ete3/ncbi_taxonomy/__init__.py", line 40, in <module>
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 56, in <module>
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "sqlite3/__init__.py", line 23, in <module>
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "sqlite3/dbapi2.py", line 27, in <module>
ModuleNotFoundError: No module named '_sqlite3'
[7377] Failed to execute script torBot

**Comment by PSNAppz** [comment]
Try this: [StackOverFlow](https://stackoverflow.com/a/19748196/4161385)

**Comment by samitbrc** [comment]
Thanks PSN....it worked.....
now I'm able to see the result of python3 torBot.py -h
now can you help me with steps to proceed further....?
I've used the command python3 torbot.py -u http://weevil.info/

1. It is showing multiple entries.........now I want to understand what is the actual use of crwaling this and get the output?
2. Is that possible to find darkweb footprints for a website using this tool???

please help

**Comment by PSNAppz** [comment]
@samitbrc Great!
1. You will get a list of URLs crawled from the page and you can see the tree output. Along with this, you can get the contents of the page, emails etc. So basically, it's an OSINT tool. 
2. We are working on that. Currently, this tool can be used for crawling both dark web and surface web pages.
@KingAkeem can give some more details.

**Comment by yekutielyehuda** [comment]
I got the next errors: 

```
/home/kali/TorBot/torbot/modules/linktree.py:64: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = BeautifulSoup(resp.text, "html.parser")
/home/kali/TorBot/torbot/modules/nlp/main.py:17: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = BeautifulSoup(data, features="html.parser")
/home/kali/TorBot/torbot/modules/linktree.py:175: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = BeautifulSoup(html, "html.parser")
^CInterrupt received! Exiting cleanly...
```
how can i fix this?

**Comment by KingAkeem** [comment]
These are warnings that are set by BeautifulSoup, the program should still run to completion. I could possibly set the log level to a lower setting so they aren't displayed but it's not a breaking change currently. You can create a new ticket for this warning and I'll take a look at it.
