### ISSUE TITLE
ImportError: cannot import name 'TreeStyle'

### ISSUE THREAD

**Issue by d0n601** [DedSecInside/TorBot#182]
**Describe the bug**
Seems to be throwing an ImportError, `ImportError: cannot import name 'TreeStyle'`.

**To Reproduce**
1. Install requirements via `pip3 install -r requirements.txt`
2.  `python3 ./torBot.py`

**Expected behavior**
I'm expecting to see the help documentation,
```
usage: torBot.py [-h] [-v] [--update] [-q] [-u URL] [-s] [-m] [-e EXTENSION]
                 [-l] [-i]

optional arguments:
  -h, --help            Show this help message and exit
  -v, --version         Show current version of TorBot.
  --update              Update TorBot to the latest stable version
  -q, --quiet           Prevent header from displaying
  -u URL, --url URL     Specifiy a website link to crawl, currently returns links on that page
  -s, --save            Save results to a file in json format
  -m, --mail            Get e-mail addresses from the crawled sites
  -e EXTENSION, --extension EXTENSION
                        Specifiy additional website extensions to the
                        list(.com or .org etc)
  -l, --live            Check if websites are live or not (slow)
  -i, --info            Info displays basic info of the scanned site (very
                        slow)` 
```

**Screenshots**
```
root@torbot:~/TorBot# python3 torBot.py
Traceback (most recent call last):
  File "torBot.py", line 10, in <module>
    from modules.analyzer import LinkTree
  File "/root/TorBot/modules/analyzer.py", line 6, in <module>
    from ete3 import Tree, TreeStyle, TextFace, add_face_to_node
ImportError: cannot import name 'TreeStyle'
```

**System Information:**
 - OS: Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-66-generic x86_64)
 - Python Version: Python 3.6.9

**Comment by d0n601** [comment]
Is it possible to run TorBot on Ubuntu Server? I'm seeing issues related to what appears to be a graphics library?

**Comment by PSNAppz** [comment]
It should work on Ubuntu server as well. 

Did you `pip install PyQt5`?

**Comment by PSNAppz** [comment]
Closing this. Feel free to re-open if required
