### ISSUE TITLE
not started

### ISSUE THREAD

**Issue by pretech86** [DedSecInside/TorBot#183]
when i try ./torbot i get 

Traceback (most recent call last):
  File "torBot.py", line 10, in <module>
    from modules.analyzer import LinkTree
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    #
  File "modules/analyzer.py", line 6, in <module>
    from ete3 import Tree, TreeStyle, TextFace, add_face_to_node
ModuleNotFoundError: No module named 'ete3'
[19381] Failed to execute script torBot

**Comment by PSNAppz** [comment]
Refer:[here]( https://github.com/DedSecInside/TorBot/issues/177)

**Comment by pretech86** [comment]
i tried python3 torBot.py and get the following 
Traceback (most recent call last):
  File "torBot.py", line 10, in <module>
    from modules.analyzer import LinkTree
  File "/root/tools/reconnesence/TorBot.v1.3/TorBot v1.3/modules/analyzer.py", line 6, in <module>
    from ete3 import Tree, TreeStyle, TextFace, add_face_to_node
ImportError: cannot import name 'TreeStyle' from 'ete3' (/usr/local/lib/python3.8/dist-packages/ete3/__init__.py)

pip install ete3 i get 
Requirement already satisfied: ete3 in /usr/local/lib/python3.8/dist-packages (3.1.1)

i try with python3.8 , python3.6 also but not run

**Comment by PSNAppz** [comment]
Try in a virtual environment. I think all your python versions and packages are clashed.

**Comment by pretech86** [comment]
How i use virtual environment

**Comment by PSNAppz** [comment]
Refer [this](https://help.dreamhost.com/hc/en-us/articles/115000695551-Installing-and-using-virtualenv-with-Python-3)
