### ISSUE TITLE
Connection Refuse Error

### ISSUE THREAD

**Issue by Balloon666** [DedSecInside/TorBot#293]
**Describe the bug**
When I was trying to run TorBot to test crawling data from the TorBot github website, after showing the torbot tool logo in my terminal, I met bugs " ConnectionRefusedError: [Errno 111] Connection refused".

"The detailed error message is listed below:

Traceback (most recent call last):
  File "/home/bilun/.cache/pypoetry/virtualenvs/torbot-tVpR5tbw-py3.10/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/bilun/.cache/pypoetry/virtualenvs/torbot-tVpR5tbw-py3.10/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/bilun/.cache/pypoetry/virtualenvs/torbot-tVpR5tbw-py3.10/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bilun/TorBot/run.py", line 8, in <module>
    torbot.perform_action()
  File "/home/bilun/TorBot/torbot/main.py", line 103, in perform_action
    link_io.print_tor_ip_address()
  File "/home/bilun/TorBot/torbot/modules/link_io.py", line 21, in print_tor_ip_address
    ip_string = color(get_ip(), 'yellow')
  File "/home/bilun/TorBot/torbot/modules/api.py", line 34, in get_ip
    resp = requests.get(url)
  File "/home/bilun/.cache/pypoetry/virtualenvs/torbot-tVpR5tbw-py3.10/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/bilun/.cache/pypoetry/virtualenvs/torbot-tVpR5tbw-py3.10/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/bilun/.cache/pypoetry/virtualenvs/torbot-tVpR5tbw-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bilun/.cache/pypoetry/virtualenvs/torbot-tVpR5tbw-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/bilun/.cache/pypoetry/virtualenvs/torbot-tVpR5tbw-py3.10/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /ip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb7b6e350>: Failed to establish a new connection: [Errno 111] Connection refused'))"

**To Reproduce**
1. After Install the tools and the needed dependency, I ran "poetry run python run.py -u https://github.com/DedSecInside/TorBot".
2. It showed the error messages.
3. I have checked my Tor status, it is active.
4. I have tried two approaches to solve it but both failed.  (1) added "DNSPort 9053, AutomapHostsOnResolve 1" in "/etc/tor/torrc" (2) in the same torrc file, uncommented the "#HiddenServiceDir /var/lib/tor/hidden_service/
#HiddenServicePort 80 127.0.0.1:80", and changed "HiddenServicePort 80 127.0.0.1:80" to "HiddenServicePort 53 127.0.0.1:53". 
But neither approach worked.

**Expected behavior**

**Screenshots**
![image](https://github.com/DedSecInside/TorBot/assets/144960008/a5cf9ab7-570a-4cbd-9e58-5cfe623e4d07)
![image](https://github.com/DedSecInside/TorBot/assets/144960008/36195538-c5cb-4bf4-8e6f-fd392e88a6aa)

**Desktop (please complete the following information):**
ubuntu system

**Comment by KingAkeem** [comment]
It looks like `gotor` isn't running, that's what `localhost:8081` refers to.
