### ISSUE TITLE
Error using -i flag

### ISSUE THREAD

**Issue by Agostinelli** [DedSecInside/TorBoT#38]
How does this flag work?

I have tried: `python3 torBot.py -i `and the results are equal to `python3 torBot.py`

However when I run it with an url, I get this error: 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/socks.py", line 813, in connect
    negotiate(self, dest_addr, dest_port)
  File "/usr/local/lib/python3.5/dist-packages/socks.py", line 477, in _negotiate_SOCKS5
    CONNECT, dest_addr)
  File "/usr/local/lib/python3.5/dist-packages/socks.py", line 552, in _SOCKS5_request
    raise SOCKS5Error("{0:#04x}: {1}".format(status, error))
socks.SOCKS5Error: 0x06: TTL expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
  File "/usr/local/lib/python3.5/dist-packages/socks.py", line 96, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/socks.py", line 817, in connect
    raise GeneralProxyError("Socket error", error)
socks.GeneralProxyError: Socket error: 0x06: TTL expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "torBot.py", line 130, in <module>
    main()
  File "torBot.py", line 116, in main
    b = readPage(link)
  File "/root/torbot/TorBoT/modules/pagereader.py", line 11, in readPage
    response = urllib.request.urlopen(req)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error Socket error: 0x06: TTL expired>
```

**Comment by PSNAppz** [comment]
Hello @Agostinelli,
Thank you for reporting the issue. We'll check this and let you know about it asap.

**Comment by PSNAppz** [comment]
@Agostinelli Bug Confirmed. 
The` -i flag` is currently under development stage.
Please try `python3 torBot.py -u http://3g2upl4pq6kufc4m.onion` and paste the stack trace (if there is any) here.

Thank you for reporting the issue.

**Comment by Agostinelli** [comment]
Here it is: 

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/socks.py", line 813, in connect
    negotiate(self, dest_addr, dest_port)
  File "/usr/local/lib/python3.5/dist-packages/socks.py", line 477, in _negotiate_SOCKS5
    CONNECT, dest_addr)
  File "/usr/local/lib/python3.5/dist-packages/socks.py", line 552, in _SOCKS5_request
    raise SOCKS5Error("{0:#04x}: {1}".format(status, error))
socks.SOCKS5Error: 0x06: TTL expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
  File "/usr/local/lib/python3.5/dist-packages/socks.py", line 96, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/socks.py", line 817, in connect
    raise GeneralProxyError("Socket error", error)
socks.GeneralProxyError: Socket error: 0x06: TTL expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "torBot.py", line 130, in <module>
    main()
  File "torBot.py", line 116, in main
    b = readPage(link)
  File "/root/torbot/TorBoT/modules/pagereader.py", line 11, in readPage
    response = urllib.request.urlopen(req)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error Socket error: 0x06: TTL expired>

By the way, I would gladly help to resolve this/other issues, but I am currently working on the Wiki Page.

**Comment by PSNAppz** [comment]
@Agostinelli Good to hear that. So can I assign this issue to you?

**Comment by Agostinelli** [comment]
Yes. I will do my best.

**Comment by Agostinelli** [comment]
Could you please assign me the #37 as well?

**Comment by PSNAppz** [comment]
@Agostinelli Ok done !
