### ISSUE TITLE
Torbot breaks for non onion site

### ISSUE THREAD

**Issue by agrepravin** [DedSecInside/TorBoT#64]
usage:
python torBot.py -u www.google.com

Error:
Traceback (most recent call last):
  File "torBot.py", line 188, in <module>
    main()
  File "torBot.py", line 162, in main
    html_content = pagereader.readPage(link)
  File "/root/tor/TorEnv/TorBoT/modules/pagereader.py", line 9, in readPage
    req = urllib.request.Request(site, None, headers)
  File "/usr/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/usr/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/usr/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'www.google.com'

**Comment by PSNAppz** [comment]
`python3 torBot.py -u https://www.google.com
`
Try this

**Comment by agrepravin** [comment]
we will need to alert user to use https or they haven't done we will need to prepend it before passing it to pagereader

**Comment by PSNAppz** [comment]
Yea if you like to find a solution for that you can reopen this issue and start working on a fix

**Comment by agrepravin** [comment]
yeah will try to workout something for this

**Comment by PSNAppz** [comment]
Great !

**Comment by PSNAppz** [comment]
Fixed
