### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by shivankar-madaan** [DedSecInside/TorBoT#77]
When I run this (with the Tor service being down) [DEV branch]
` python torBot.py -u http://torlinkbgs6aabns.onion/`
I get this error
```                       + "LICENSE: GNU Public License" +
Attempting to connect to https://check.torproject.org/
Attempting to connect to https://check.torproject.org/
Attempting to connect to https://check.torproject.org/
Traceback (most recent call last):
  File "torBot.py", line 186, in <module>
    main(conn=True)
  File "torBot.py", line 158, in main
    print("Tor IP Address :", pagereader.get_ip())
  File "/tmp/TorBoT/modules/pagereader.py", line 102, in get_ip
    pg = page.find('strong')
AttributeError: 'NoneType' object has no attribute 'find'
```
its got to do something to do with
```
    if err == HTTPError:
        raise("There has been an HTTP error after three attempts.")
    if err == ConnectionError:
        raise("There has been a connection error after three attempts.")
```

in pagereader.py
Can we fix this?

**Comment by PSNAppz** [comment]
@shivankar-madaan Thank you for raising the issue. @Agostinelli  Please confirm this.

**Comment by KingAkeem** [comment]
I can't reproduce the error, I just tried it out and it worked fine for me. Could you give me some more details of your system?

**Comment by shivankar-madaan** [comment]
@KingAkeem did you have the Tor service as not running?

**Comment by KingAkeem** [comment]
No it's running, if it weren't running then I wouldn't be able to connect to the .onion website.

**Comment by shivankar-madaan** [comment]
Here are my details
```                       + "LICENSE: GNU Public License" +
Attempting to connect to https://check.torproject.org/
Attempting to connect to https://check.torproject.org/
Attempting to connect to https://check.torproject.org/
Traceback (most recent call last):
  File "torBot.py", line 186, in <module>
    main(conn=True)
  File "torBot.py", line 158, in main
    print("Tor IP Address :", pagereader.get_ip())
  File "/tmp/TorBoT/modules/pagereader.py", line 102, in get_ip
    pg = page.find('strong')
AttributeError: 'NoneType' object has no attribute 'find'
[root@ip-10-96-16-124 TorBoT]# python -V
Python 3.6.0
[root@ip-10-96-16-124 TorBoT]#
[root@ip-10-96-16-124 TorBoT]# service tor status
tor is not running```

**Comment by PSNAppz** [comment]
@KingAkeem He is running without the tor services being started. 
@shivankar-madaan Are you saying that to handle the exception in a neat way?

**Comment by shivankar-madaan** [comment]
yes @PSNAppz

**Comment by PSNAppz** [comment]
I think thats a good idea. @KingAkeem What do you think?

**Comment by KingAkeem** [comment]
I understand now, I thought you were saying that it didn't work correctly. What would you think a better method of handling the exception be? Currently it attempts to connect to a site three times, then raises an error which gives a description that tells the user how many times the connection was attempted and why it failed.

**Comment by shivankar-madaan** [comment]
I am not sure about how right the solution is to be
But the I think if condition is not rightly written
It should be modified something like this
```
    if type(err) == HTTPError:
        raise("There has been an HTTP error after three attempts.")
    if type(err) == ConnectionError:
        raise("There has been a connection error after three attempts.")
```
And with this we get a different error
```Attempting to connect to https://check.torproject.org/
Attempting to connect to https://check.torproject.org/
Attempting to connect to https://check.torproject.org/
Traceback (most recent call last):
  File "torBot.py", line 186, in <module>
    main(conn=True)
  File "torBot.py", line 158, in main
    print("Tor IP Address :", pagereader.get_ip())
  File "/tmp/TorBoT/modules/pagereader.py", line 103, in get_ip
    page = read_first_page('https://check.torproject.org/')
  File "/tmp/TorBoT/modules/pagereader.py", line 52, in read_first_page
    raise("There has been a connection error after three attempts.")
TypeError: exceptions must derive from BaseException```

**Comment by KingAkeem** [comment]
@shivankar-madaan `type(err) == ConnectionError` returns False. The correct form is `err == ConnectionError`

**Comment by PSNAppz** [comment]
@shivankar-madaan Would you like to talk in our slack channel? If yes, please post your emil for the invitation.

**Comment by shivankar-madaan** [comment]
sure @PSNAppz 
mrxlimitless@gmaildotcom

**Comment by shivankar-madaan** [comment]
@KingAkeem with type(err) the code flow is able to reach to the `raise("There has been a connection error after three attempts")`
But with the usual code we are reaching to
```Traceback (most recent call last):
  File "torBot.py", line 186, in <module>
    main(conn=True)
  File "torBot.py", line 158, in main
    print("Tor IP Address :", pagereader.get_ip())
  File "/tmp/TorBoT/modules/pagereader.py", line 102, in get_ip
    pg = page.find('strong')
AttributeError: 'NoneType' object has no attribute 'find'```

**Comment by PSNAppz** [comment]
@shivankar-madaan Invited

**Comment by shivankar-madaan** [comment]
thanks @PSNAppz

**Comment by PSNAppz** [comment]
Referencing PR #78
